################################# Default configuration ###################
baseURL = "/"
title = "Upstage"
theme = "meghna-hugo"
defaultContentLanguageInSubdir = true

# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
# [[menu.main]]
# name = "about"
# URL = "about"
# weight = 1

# [[menu.main]]
# name = "news"
# URL = "news"
# weight = 2

# [[menu.static]]
# name = "careers"
# URL = "https://careers.upstage.ai"
# weight = 3


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Upstage"
author = "Upstage"
# Google Analytics
google_analytics_id = "UA-179083713-1"
# post share
post_share = false

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

#
############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/upstageai"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/upstageai"

# NOTE: Needs 100+ subscribers to obtain a custom url https://support.google.com/youtube/answer/2657968?hl=en
[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCXJY5PPAToqqSketm5_PrDw"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/upstageai"

#
################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2020 Upstage"

################################ Korean Language ########################
[Languages.ko]
languageName = "Korean"
languageCode = "ko-kr"
contentDir = "content/korean"
weight = 2
home = "처음으로"
copyright = "Copyright &copy; 2020 Upstage"
